-- Retention sweep query index (backend gap, retention t_91d0644f review).
-- Hand-written migration following the journal convention; applied by
-- `wrangler d1 migrations apply` and replayed by the db-runtime test harness.
--
-- runRetentionSweep (db/retention.ts) resolves the R2 "rejection decision
-- date" with
--   WHERE entity = 'camera' AND action = 'reject'
--   GROUP BY entity_id
-- over the append-only moderation_events audit trail. The existing indexes
-- (moderation_events_created_at_idx (created_at, id), and the 0012
-- (entity, entity_id) lookup) do not serve the action filter, so the query
-- scans the whole audit log once the trail grows (the R2 sweep re-runs it on
-- every daily tick). (entity, action, entity_id) makes the filter an index
-- seek and covers the GROUP BY key without a sort (review t_eed5f080
-- suggestion: widen the index to the group-by column).
--
-- Numbered 0018: main already ships 0017_remove_demo_seed (#115); this index
-- was previously staged as 0015/0016/0017 but renumbered after the rebase on
-- main (t_0a3a71b0).

CREATE INDEX `moderation_events_entity_action_idx` ON `moderation_events` (`entity`, `action`, `entity_id`);
