-- 0043_remove_photo_uploads.sql
-- CEO decision 2026-08-08: photo evidence upload is removed from the system
-- entirely (API, db, UI, legal). The `photos` table (metadata-only; image
-- bytes lived in the R2 bucket `PHOTOS`) is dropped. Existing R2 objects are
-- NOT deleted — the code that read them is gone, the bucket data is left in
-- place (see the PR summary).
--
-- Related tables/migrations that disappear with it: the pending-photo quota
-- indexes (0013), the contributor_created index (0025, shared with cameras)
-- and the moderation 'photo' entity events stay as historical rows — only the
-- source table is dropped.
DROP TABLE IF EXISTS photos;
