import { getD1 } from "./cameras";
import { randomBase64Url, sha256Hex } from "./auth";

/**
 * WebAuthn passkeys, ceremony challenges and one-time recovery codes
 * (multi-method auth Fase C, t_36989e06; AUTH_OPTIONS.md §3).
 *
 * Security properties, following the same rules as db/auth.ts (ADR 0013):
 *  - Only the SHA-256 of the base64url challenge is stored: a database leak
 *    cannot replay a live ceremony. The raw challenge is generated by the
 *    route, returned to the browser in the WebAuthn options, echoed back in
 *    `clientDataJSON`, and the consume lookup hashes the echoed value.
 *  - Challenges expire 10 minutes after creation (`expires_at`) and are
 *    single-use: consume is an atomic conditional UPDATE on `used_at IS
 *    NULL` (anti-replay). The expiry sweep is a bounded DELETE on
 *    `expires_at` — D1 has no TTL, so the store manages expiry explicitly
 *    (same pattern as `email_verification_tokens`).
 *  - Only the COSE public key of a passkey is stored — the private key
 *    never leaves the user's authenticator. `counter` is the WebAuthn
 *    signature counter; the login route enforces a strict increase to
 *    detect cloned authenticators (anti-replay).
 *  - The 10 recovery codes issued at enrollment are stored hashed
 *    (SHA-256), one row per code, single-use (`used_at`). The plaintext
 *    codes are returned to the caller exactly once, at issue time.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Challenge lifetime: 10 minutes (AUTH_OPTIONS.md §3 suggests 5–10 min). */
export const WEBAUTHN_CHALLENGE_TTL_MS = 10 * 60 * 1000;

/** Number of one-time recovery codes issued at passkey enrollment. */
export const RECOVERY_CODE_COUNT = 10;

/** Entropy per recovery code: 12 random bytes = 96 bits. */
const RECOVERY_CODE_BYTES = 12;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type WebAuthnChallengeKind = "register" | "login";

export type WebAuthnChallenge = {
  id: number;
  challengeHash: string;
  kind: WebAuthnChallengeKind;
  contributorId: number | null;
  userHandle: string | null;
  createdAt: string;
  expiresAt: string;
  usedAt: string | null;
};

export type Passkey = {
  id: number;
  contributorId: number;
  credentialId: string;
  publicKey: string;
  counter: number;
  transports: string | null;
  createdAt: string;
};

/** What the API ever returns: the COSE public key never leaves the db layer. */
export type PublicPasskey = {
  id: number;
  credentialId: string;
  transports: string | null;
  createdAt: string;
};

// ---------------------------------------------------------------------------
// Recovery codes
// ---------------------------------------------------------------------------

/**
 * Generate a plaintext recovery code in the form `xxxx-xxxx-xxxx-xxxx`
 * (12 random bytes, base64url, grouped by 4 for readability).
 */
export function generateRecoveryCode(): string {
  const raw = randomBase64Url(RECOVERY_CODE_BYTES);
  return raw.match(/.{1,4}/g)?.join("-") ?? raw;
}

/** SHA-256 hex of a recovery code — the only form stored in the database. */
export function recoveryCodeHash(code: string): Promise<string> {
  return sha256Hex(code);
}

// ---------------------------------------------------------------------------
// WebAuthn ceremony challenges
// ---------------------------------------------------------------------------

const challengeColumns =
  "id, challenge_hash AS challengeHash, kind, contributor_id AS contributorId, user_handle AS userHandle, created_at AS createdAt, expires_at AS expiresAt, used_at AS usedAt";

/**
 * Store a new ceremony challenge. Only the SHA-256 of the raw base64url
 * challenge is persisted; `now` and `ttlMs` are injectable for deterministic
 * tests (same convention as createSession in db/auth.ts).
 */
export async function createWebAuthnChallenge(
  input: {
    challenge: string;
    kind: WebAuthnChallengeKind;
    contributorId?: number | null;
    userHandle?: string | null;
    now?: string;
    ttlMs?: number;
  },
): Promise<WebAuthnChallenge> {
  const d1 = await getD1();
  const now = input.now ?? new Date().toISOString();
  const ttlMs = input.ttlMs ?? WEBAUTHN_CHALLENGE_TTL_MS;
  const challengeHash = await sha256Hex(input.challenge);
  const expiresAt = new Date(Date.parse(now) + ttlMs).toISOString();
  const row = await d1
    .prepare(
      `INSERT INTO webauthn_challenges (challenge_hash, kind, contributor_id, user_handle, created_at, expires_at)
       VALUES (?, ?, ?, ?, ?, ?)
       RETURNING ${challengeColumns}`,
    )
    .bind(
      challengeHash,
      input.kind,
      input.contributorId ?? null,
      input.userHandle ?? null,
      now,
      expiresAt,
    )
    .first<WebAuthnChallenge>();
  if (!row) throw new Error("WebAuthn challenge could not be stored");
  return row;
}

/**
 * Atomically consume a challenge: hashes the echoed raw challenge and marks
 * the matching row used, but ONLY when it exists, has not expired and has
 * not been used yet. Returns the row on success, null on unknown/expired/
 * already-used — the route maps null to a generic failure so responses do
 * not reveal why the ceremony was rejected.
 */
export async function consumeWebAuthnChallenge(
  challenge: string,
  now: string = new Date().toISOString(),
): Promise<WebAuthnChallenge | null> {
  const d1 = await getD1();
  const challengeHash = await sha256Hex(challenge);
  return d1
    .prepare(
      `UPDATE webauthn_challenges
       SET used_at = ?
       WHERE challenge_hash = ? AND expires_at > ? AND used_at IS NULL
       RETURNING ${challengeColumns}`,
    )
    .bind(now, challengeHash, now)
    .first<WebAuthnChallenge>();
}

/**
 * Expiry sweep: delete every expired challenge row. Bounded by the 10-minute
 * TTL (never a large table); called opportunistically on each begin ceremony.
 * Returns the number of rows removed.
 */
export async function sweepExpiredWebAuthnChallenges(
  now: string = new Date().toISOString(),
): Promise<number> {
  const d1 = await getD1();
  const result = (await d1
    .prepare("DELETE FROM webauthn_challenges WHERE expires_at < ?")
    .bind(now)
    .run()) as { meta: { changes: number } };
  return result.meta.changes;
}

// ---------------------------------------------------------------------------
// Passkeys
// ---------------------------------------------------------------------------

const passkeyColumns =
  "id, contributor_id AS contributorId, credential_id AS credentialId, public_key AS publicKey, counter, transports, created_at AS createdAt";

const publicPasskeyColumns =
  "id, credential_id AS credentialId, transports, created_at AS createdAt";

/** Every passkey the contributor has enrolled (no COSE key in the response). */
export async function listPasskeys(contributorId: number): Promise<PublicPasskey[]> {
  const d1 = await getD1();
  const result = await d1
    .prepare(`SELECT ${publicPasskeyColumns} FROM passkeys WHERE contributor_id = ? ORDER BY id`)
    .bind(contributorId)
    .all<PublicPasskey>();
  return result.results;
}

/**
 * Full passkey row including the COSE public key — used only by the login
 * verifier. The lookup is by the globally unique `credential_id`, which is
 * what the assertion response carries.
 */
export async function findPasskeyByCredentialId(
  credentialId: string,
): Promise<Passkey | null> {
  const d1 = await getD1();
  return d1
    .prepare(`SELECT ${passkeyColumns} FROM passkeys WHERE credential_id = ?`)
    .bind(credentialId)
    .first<Passkey>();
}

/**
 * Store a verified registration credential. The credential_id is globally
 * UNIQUE per relying party: a duplicate (re-enrollment of the same key, or a
 * race between two ceremonies) fails here and returns null — the route maps
 * it to 409. `counter` is the sign count from the attestation (SimpleWebAuthn
 * reports it as `registrationInfo.counter`).
 */
export async function createPasskey(input: {
  contributorId: number;
  credentialId: string;
  publicKey: string;
  counter: number;
  transports: string[] | undefined;
  now?: string;
}): Promise<Passkey | null> {
  const d1 = await getD1();
  const now = input.now ?? new Date().toISOString();
  const transports =
    input.transports && input.transports.length > 0
      ? JSON.stringify(input.transports)
      : null;
  return d1
    .prepare(
      `INSERT INTO passkeys (contributor_id, credential_id, public_key, counter, transports, created_at)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT (credential_id) DO NOTHING
       RETURNING ${passkeyColumns}`,
    )
    .bind(input.contributorId, input.credentialId, input.publicKey, input.counter, transports, now)
    .first<Passkey>();
}

/**
 * Record the new signature counter after a verified assertion. The login
 * route enforces a strict increase BEFORE calling this (anti-replay for
 * cloned authenticators); this function only persists the accepted value.
 */
export async function updatePasskeyCounter(
  id: number,
  counter: number,
): Promise<void> {
  const d1 = await getD1();
  await d1.prepare("UPDATE passkeys SET counter = ? WHERE id = ?").bind(counter, id).run();
}

/** Delete one of the contributor's own passkeys. Returns whether a row went. */
export async function deletePasskey(
  contributorId: number,
  credentialId: string,
): Promise<boolean> {
  const d1 = await getD1();
  const result = (await d1
    .prepare("DELETE FROM passkeys WHERE contributor_id = ? AND credential_id = ?")
    .bind(contributorId, credentialId)
    .run()) as { meta: { changes: number } };
  return result.meta.changes > 0;
}

// ---------------------------------------------------------------------------
// Recovery codes
// ---------------------------------------------------------------------------

/**
 * Issue a fresh set of recovery codes (10 by default) for a contributor.
 * Any previous UNUSED codes are revoked first (re-issue semantics: the old
 * codes die with the batch that produced them). Returns the plaintext codes
 * — the ONLY time they are ever returned; the rows store only the hashes.
 */
export async function issueRecoveryCodes(
  contributorId: number,
  count: number = RECOVERY_CODE_COUNT,
  now: string = new Date().toISOString(),
): Promise<string[]> {
  const d1 = await getD1();
  await d1
    .prepare("DELETE FROM recovery_codes WHERE contributor_id = ? AND used_at IS NULL")
    .bind(contributorId)
    .run();
  const codes: string[] = [];
  for (let index = 0; index < count; index += 1) {
    const code = generateRecoveryCode();
    codes.push(code);
    await d1
      .prepare(
        "INSERT INTO recovery_codes (contributor_id, code_hash, created_at) VALUES (?, ?, ?)",
      )
      .bind(contributorId, await recoveryCodeHash(code), now)
      .run();
  }
  return codes;
}

/**
 * Atomically consume a single recovery code for a contributor: only an
 * existing, unused code row consumes successfully (single-use). Returns
 * false for unknown/wrong/used codes — the route answers a generic 401 so
 * responses do not reveal whether the email exists or the code was valid.
 */
export async function consumeRecoveryCode(
  contributorId: number,
  code: string,
  now: string = new Date().toISOString(),
): Promise<boolean> {
  const d1 = await getD1();
  const codeHash = await recoveryCodeHash(code);
  const result = (await d1
    .prepare(
      `UPDATE recovery_codes
       SET used_at = ?
       WHERE contributor_id = ? AND code_hash = ? AND used_at IS NULL`,
    )
    .bind(now, contributorId, codeHash)
    .run()) as { meta: { changes: number } };
  return result.meta.changes > 0;
}

/** How many unused recovery codes the contributor still has (account page). */
export async function countUnusedRecoveryCodes(contributorId: number): Promise<number> {
  const d1 = await getD1();
  const row = await d1
    .prepare(
      "SELECT COUNT(*) AS n FROM recovery_codes WHERE contributor_id = ? AND used_at IS NULL",
    )
    .bind(contributorId)
    .first<{ n: number }>();
  return Number(row?.n ?? 0);
}
